// Design system — componentes base (ver docs no topo de cada arquivo).
export { cx, ICON_STROKE } from './cx'
export { Button, IconButton, type ButtonVariant, type ButtonSize } from './Button'
export { Spinner, Skeleton, SkeletonList, Alert, EmptyState, ErrorState, QueryState } from './Feedback'
export { errorMessage } from '@/lib/errors'
export { Field } from './Field'
export { Card, PageHeader } from './Layout'
export { Badge, PositionBadge, CardIcon, LiveDot, type BadgeColor } from './Badge'
export { Avatar } from './Avatar'
export { TeamShield } from './TeamShield'
export { ScoreStrip, type StripTeam } from './ScoreStrip'
export { Stopwatch, StopwatchView } from './Stopwatch'
export { StandingsTable, type StandingsRow } from './StandingsTable'
export { Bracket, type BracketMatch } from './Bracket'
export { Modal, Sheet } from './Modal'
export { ToastProvider } from './Toast'
export { ConfirmProvider } from './ConfirmDialog'
